version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug

init:
  - ps:
    
$MainDir = 'C:\Tmp'


if ([System.IO.Directory]::Exists($MainDir)){
    cd $MainDir
}
else{
    New-Item -Path $MainDir -ItemType Directory
    cd $MainDir
}

# Get depo_tools from google repository
$url = "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
$output = "depot_tools.zip"
$start_time = Get-Date
Invoke-WebRequest -Uri $url -OutFile $output
Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"

# unzip the file
Add-Type -AssemblyName System.IO.Compression.FileSystem
function Unzip
{
    param([string]$zipfile, [string]$outpath)

    [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)
}

Unzip C:\Tmp\depot_tools.zip "C:\Tmp\depot_tools"

$env:Path = "C:\Tmp\depot_tools;$env:Path"
$env:DEPOT_TOOLS_WIN_TOOLCHAIN = "0"

cd C:\Tmp\depot_tools

gclient

cd ..

## Here, Takes time
gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git

gclient sync

before_build:
  - dotnet restore

#  - nuget install packages.config

build:
  #include_nuget_references: true
  verbosity: normal
  project: wrapper.sln 

after_build:

  - nuget push C:\projects\wrapper\wrapper\bin\x64\Debug\Wrapper.1.0.1.nupkg 4ea8694a-134a-4cbe-b553-b3c6487a64ec -Source https://www.myget.org/F/wrapper-pdfium/api/v2/package

# deploy:
#   - provider: NuGet
#     symbol_server: https://ci.appveyor.com/nuget/wrapper-8k7xixj6m22b/api/v2/package
#     api_key:
#       secure: 8avv5kgxnpoqxildqyfsnga3
#     artifact: /.*\.symbols\.nupkg/

#test_script:
#  - C:\projects\testfromnuget\TestFromNuGet\bin\x64\Debug\TestFromNuGet.exe